# Desktop outputs
monitor = DP-1,3840x2160@144,0x0,1
monitor = HDMI-A-1,disable

env = LIBVA_DRIVER_NAME,nvidia
env = NVD_BACKEND,direct
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
cursor:no_hardware_cursors = true

workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = HDMI-A-1, 6
workspace = HDMI-A-1, 7
workspace = HDMI-A-1, 8
workspace = HDMI-A-1, 9
workspace = HDMI-A-1, 10
