# RedmiBook Pro 15
monitor = eDP-1, 3200x2000@90, 0x0, 1.6

# Lid switch handling
bindl = , switch:off:Lid Switch, exec, hyprctl dispatch dpms on
bindl = , switch:on:Lid Switch, exec, hyprctl dispatch dpms off
